feat: rewrite sln in c# & upload extract to azure
Informatievlaanderen/extract-bundler pull request #46
Opened 2023-10-18 08:56 UTC by YusufMavzer

2023-10-18 09:16 UTC, jvandaal commented on src/ExtractBundler.Console/Bundlers/BaseBundler.cs
> +        Console.WriteLine(_identifier.GetValue(ZipKey.MetadataUpdatedMessage));
Shouldn't this be a log statement

2023-10-18 11:58 UTC, YusufMavzer commented on src/ExtractBundler.Console/Bundlers/BaseBundler.cs
> +        Console.WriteLine(_identifier.GetValue(ZipKey.MetadataUpdatedMessage));
my bad, zal veranderen

2023-10-18 12:31 UTC, ArneD requested changes

2023-10-18 12:31 UTC, ArneD commented on src/ExtractBundler.Console/ExtractBundler.Console.csproj
> +    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
Probably not needed here, no dependencies

2023-10-18 12:31 UTC, ArneD commented on src/ExtractBundler.Console/Bundlers/AddressBundler.cs
> +    public AddressBundler(ExtractDownloader extractDownloader, MetaDataCenterHttpClient metadataClient,
multiple lines

2023-10-18 12:31 UTC, ArneD commented on src/ExtractBundler.Console/Bundlers/BaseBundler.cs
> +    protected readonly List<string> _requiredZipArchives = new List<string>();
move above property

2023-10-18 12:31 UTC, ArneD commented on src/ExtractBundler.Console/Bundlers/FullBundler.cs
> +    public FullBundler(ExtractDownloader extractDownloader, MetaDataCenterHttpClient metadataClient,
multiple lines

2023-10-18 12:31 UTC, ArneD commented on src/ExtractBundler.Console/Bundlers/StreetNameBundler.cs
> +        S3Client s3Client, AzureBlobClient azureBlobClient) : base(extractDownloader, metadataClient, s3Client, azureBlobClient)
multiple lines

2023-10-18 12:36 UTC, YusufMavzer commented on src/ExtractBundler/FileExtensions.cs
> +    public static string EnsureDirectoryCreated(this string dirPath)
I'll remove it. Written during development for development

2023-10-18 12:54 UTC, ArneD requested changes

2023-10-18 12:54 UTC, ArneD commented on src/ExtractBundler.Console/CloudStorageClients/AzureBlobClient.cs
> +        private const int chunkSizeInBytes = 4 * 1024 * 1024; // 4 MB chunk size
Const naming Capital C

2023-10-18 12:54 UTC, ArneD commented on src/ExtractBundler.Console/CloudStorageClients/AzureBlobClient.cs
> +            CancellationToken cancellationToken = default)
multiple lines

2023-10-18 12:54 UTC, ArneD commented on src/ExtractBundler.Console/CloudStorageClients/AzureBlobClient.cs
> +    using Azure.Storage;
remove unused usings

2023-10-18 12:54 UTC, ArneD commented on src/ExtractBundler.Console/HttpClients/ExtractDownloadClient.cs
> +public sealed class ExtractDownloader
Filename <> Classname

2023-10-18 12:54 UTC, ArneD commented on src/ExtractBundler.Console/HttpClients/ExtractDownloadClient.cs
> +    private readonly Dictionary<string, ZipArchive> zipArchives = new();
`_zipArchives`

2023-10-18 12:54 UTC, ArneD commented on src/ExtractBundler.Console/HttpClients/ExtractDownloadClient.cs
> +    private async Task<ZipArchive> GetZipArchiveWithDownloadProgressAsync(HttpResponseMessage response, string fileName,
multiple lines

2023-10-18 12:54 UTC, ArneD commented on src/ExtractBundler.Console/HttpClients/MetaDataCenterHttpClient.cs
> +using Microsoft.Extensions.Configuration;
unused

2023-10-18 12:54 UTC, ArneD commented on src/ExtractBundler.Console/Processors/ExtractBundleProcessor.cs
> +using System;
unused

2023-10-19 09:14 UTC, ArneD commented on src/ExtractBundler.Console/ExtractBundler.Console.csproj
> +    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
The line is still there :)

2023-10-19 11:06 UTC, ArneD approved these changes

2023-10-19 11:06 UTC, merged

2023-10-19 15:20 UTC, basisregisters-vlaanderen commented
:tada: This PR is included in version 2.5.0 :tada:

The release is available on [GitHub release](https://github.com/Informatievlaanderen/extract-bundler/releases/tag/v2.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: